export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const USER_LOGOUT='USER_LOGOUT'

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

export const USER_DETAIL_REQUEST='USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS='USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAILED='USER_DETAIL_FAILED'

export const USER_UPDATE_PROFILE_REQUEST='USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS='USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILED='USER_UPDATE_PROFILE_FAILED'
export const USER_UPDATE_PROFILE_RESET='USER_UPDATE_PROFILE_RESET'
